export const cards = [
  {
    id: 1,
    category: "Bridge",
    title: "Bridge",
    description: "Bridge tokens to and from Ethereum with Sophon's official bridge",
    isComingSoon: false,
    link: "/bridge",
    icon: "/img/home/portal.svg",
    iconStyling: "bg-white",
    isInternal: true,
  },
  {
    id: 2,
    category: "DeFi",
    title: "SyncSwap",
    description: "Trade your tokens seamlessly",
    isComingSoon: false,
    link: "https://syncswap.xyz/sophon",
    icon: "/img/home/syncswap.png",
    iconStyling: "bg-white",
  },
  {
    id: 3,
    category: "DeFi",
    title: "The Farm",
    description: "Go to our farming program and accrue points that will become $SOPH",
    isComingSoon: false,
    link: "https://farm.sophon.xyz",
    icon: "/img/home/farm.svg",
    iconStyling: "bg-white",
  },
  {
    id: 4,
    category: "Gaming",
    title: "(((+)))",
    description: "Your mastery here may echo through the void.",
    isComingSoon: false,
    link: "https://play.sophon.xyz",
    icon: "/img/home/play.png",
  },
  {
    id: 5,
    category: "Guardian",
    title: "Guardian",
    description: "The Sophon Guardian dashboard to manage nodes and rewards",
    isComingSoon: false,
    link: "https://guardian.sophon.xyz",
    icon: "/img/home/guardian.svg",
  },
  {
    id: 6,
    category: "Ticketing",
    title: "Open",
    description:
      "Bringing accessible onchain benefits to millions of event attendees, organizers and artists around the world.",
    isComingSoon: false,
    link: "https://onopen.xyz",
    iconStyling: "p-1",
    icon: "/img/home/open.svg",
  },
  {
    id: 7,
    category: "Gaming",
    title: "Gamp",
    description: "Compete with a mad squad of Gampers on major titles",
    isComingSoon: false,
    link: "https://gamp.gg",
    icon: "/img/home/gamp.svg",
  },
  {
    id: 8,
    category: "Gaming",
    title: "Lé Poker",
    description: "Free, fair poker tournaments",
    isComingSoon: false,
    link: "https://app.lepoker.io/",
    icon: "/img/home/lepoker.jpg",
  },
  {
    id: 9,
    category: "Gaming",
    title: "Petopia",
    description: "Action packed battle arena game",
    isComingSoon: false,
    link: "https://petopiagame.io/",
    icon: "/img/home/petopia.png",
  },
  {
    id: 10,
    category: "Gaming",
    title: "Pioneers of new world",
    description: "Turn-based strategy game inspired by Settlers of Catan",
    isComingSoon: false,
    link: "https://pioneers.game/",
    icon: "/img/home/pioneers.jpg",
    iconStyling: "bg-white",
  },
  {
    id: 11,
    category: "Gaming",
    title: "Animix",
    description: "Mix DNA to create fantastical pets in this fun creature collection and battle game!",
    isComingSoon: false,
    link: "https://t.me/animix_game_bot",
    icon: "/img/home/animix.svg",
    iconStyling: "bg-white",
  },
  {
    id: 12,
    category: "Wallet",
    title: "Safe",
    description: "The leading and widely used multisig",
    isComingSoon: false,
    link: "https://safe.sophon.xyz",
    icon: "/img/home/safe.svg",
  },
  {
    id: 13,
    category: "Bridge",
    title: "Layerswap",
    description: "Fast and reliable cross-chain crypto transfers",
    isComingSoon: false,
    link: "https://layerswap.io/app",
    iconStyling: "p-2",
    icon: "/img/home/layerswap.svg",
  },
  {
    id: 14,
    category: "AI",
    title: "NOVA",
    description: "The AI Agent for AI Agents. Powered by Anomaly",
    isComingSoon: false,
    link: "https://terminal.poweredbynova.ai/",
    icon: "/img/home/nova.jpg",
    iconStyling: "p-1",
  },
  {
    id: 15,
    category: "DePIN",
    title: "Aethir",
    description: "On-demand GPU computing",
    isComingSoon: false,
    link: "https://aethir.com/",
    icon: "/img/home/aethir.png",
    iconStyling: "bg-white",
  },
  {
    id: 16,
    category: "Explorer",
    title: "Explorer",
    description: "Browse through Sophon's transactions, blocks, tokens, and more",
    isComingSoon: false,
    link: "https://explorer.sophon.xyz",
    icon: "/img/home/explorer.svg",
    iconStyling: "bg-white",
  },
  {
    id: 17,
    category: "Dev",
    title: "Dev Tooling",
    description: "Discover our rich ecosystem for developer",
    isComingSoon: false,
    link: "https://docs.sophon.xyz/build/partners/overview",
    icon: "/img/home/docs.svg",
  },

  {
    id: 18,
    category: "Betting",
    title: "Rivalry",
    description: "The ultimate iGaming betting platform made by gamers for gamers",
    isComingSoon: true,
    icon: "/img/home/rivalry.svg",
    iconStyling: "p-1",
  },

  {
    id: 19,
    category: "DeFi",
    title: "NooN",
    description: "The most intelligent and fair yield generating stablecoin",
    isComingSoon: true,
    icon: "/img/home/noon.svg",
    iconStyling: "bg-white",
  },
  {
    id: 20,
    category: "Gaming",
    title: "Brutal Knights",
    description: "An extraction-roguelike strategy game with web3-centric mechanics and emphasis on F2P",
    isComingSoon: true,
    icon: "/img/home/brutal.png",
    iconStyling: "bg-white",
  },
];
