export const cards = [
  {
    id: 1,
    category: "Security",
    title: "Safe",
    description: "Secure your assets by using the most adopted multisignature solution.",
    isComingSoon: false,
    link: "https://sophon.xyz",
    icon: "/img/placeholder.svg",
  },
  {
    id: 2,
    category: "Security",
    title: "Safe",
    description: "Secure your assets by using the most adopted multisignature solution.",
    isComingSoon: false,
    link: "https://sophon.xyz",
    icon: "/img/placeholder.svg",
  },
  {
    id: 3,
    category: "Security",
    title: "Safe",
    description: "Secure your assets by using the most adopted multisignature solution.",
    isComingSoon: false,
    link: "https://sophon.xyz",
    icon: "/img/placeholder.svg",
  },
  {
    id: 4,
    category: "Security",
    title: "Safe",
    description: "Secure your assets by using the most adopted multisignature solution.",
    isComingSoon: false,
    link: "https://sophon.xyz",
    icon: "/img/placeholder.svg",
  },
  {
    id: 5,
    category: "Security",
    title: "Safe",
    description: "Secure your assets by using the most adopted multisignature solution.",
    isComingSoon: false,
    link: "https://sophon.xyz",
    icon: "/img/placeholder.svg",
  },
  {
    id: 6,
    category: "Security",
    title: "Safe",
    description: "Secure your assets by using the most adopted multisignature solution.",
    isComingSoon: true,
    icon: "/img/placeholder.svg",
  },
  {
    id: 7,
    category: "Security",
    title: "Safe",
    description: "Secure your assets by using the most adopted multisignature solution.",
    isComingSoon: true,
    icon: "/img/placeholder.svg",
  },
  {
    id: 8,
    category: "Security",
    title: "Safe",
    description: "Secure your assets by using the most adopted multisignature solution.",
    isComingSoon: true,
    icon: "/img/placeholder.svg",
  },
];
