export const cards = [
  {
    category: "Sophon Essentials",
    title: "Bridge",
    description: "Bridge tokens to and from Ethereum with Sophon's official bridge",
    isComingSoon: false,
    link: "/bridge",
    icon: "/img/home/portal.svg",
    iconStyling: "bg-white",
    isInternal: true,
  },
  {
    category: "DeFi",
    title: "SyncSwap",
    description: "Trade your tokens seamlessly",
    isComingSoon: false,
    link: "https://syncswap.xyz/sophon",
    icon: "/img/home/syncswap.png",
    iconStyling: "bg-white",
  },
  {
    category: "DeFi",
    title: "The Farm",
    description: "Farm on Sophon and accrue points that will become $SOPH",
    isComingSoon: false,
    link: "https://farm.sophon.xyz",
    icon: "/img/home/farm.svg",
    iconStyling: "bg-white",
  },
  {
    category: "Gaming",
    title: "(((+)))",
    description: "Your mastery here may echo through the void",
    isComingSoon: false,
    link: "https://play.sophon.xyz",
    icon: "/img/home/play.png",
  },
  {
    category: "Sophon Essentials",
    title: "Guardian",
    description: "Manage your nodes and rewards via Sophon's Guardian App",
    isComingSoon: false,
    link: "https://guardian.sophon.xyz",
    icon: "/img/home/guardian.svg",
  },
  {
    category: "Events",
    title: "OPEN",
    description:
      "Bringing accessible onchain benefits to millions of event attendees, organizers and artists around the world",
    isComingSoon: false,
    link: "https://onopen.xyz",
    iconStyling: "p-1",
    icon: "/img/home/open.svg",
  },
  {
    category: "Gaming",
    title: "GAMP",
    description: "Compete with players around the world across a wide range of games",
    isComingSoon: false,
    link: "https://gamp.gg",
    icon: "/img/home/gamp.svg",
  },
  {
    category: "Casino",
    title: "Lé Poker",
    description: "Free, fair poker tournaments",
    isComingSoon: false,
    link: "https://app.lepoker.io/",
    icon: "/img/home/lepoker.jpg",
  },
  {
    category: "Gaming",
    title: "Petopia",
    description: "An intense top-down roguelite shooter available on Android and iOS",
    isComingSoon: false,
    link: "https://petopiagame.io/",
    icon: "/img/home/petopia.png",
  },
  {
    category: "Gaming",
    title: "Pioneers of New World",
    description: "Turn-based strategy game inspired by Settlers of Catan",
    isComingSoon: false,
    link: "https://pioneers.game/",
    icon: "/img/home/pioneers.jpg",
    iconStyling: "bg-white",
  },
  {
    category: "Gaming",
    title: "Animix",
    description: "Mix DNA to create fantastical pets in this fun creature collection and battle game",
    isComingSoon: false,
    link: "https://t.me/animix_game_bot",
    icon: "/img/home/animix.svg",
    iconStyling: "bg-white",
  },
  {
    category: "Gaming",
    title: "SPHNX",
    description: "Gamified AI red teaming platform",
    link: "https://SPHNX.ai",
    icon: "/img/home/sphnx.png",
  },
  {
    category: "Developers",
    title: "Safe",
    description: "The leading and widely used multisig",
    isComingSoon: false,
    link: "https://safe.sophon.xyz",
    icon: "/img/home/safe.svg",
  },
  {
    category: "Sophon Essentials",
    title: "Layerswap",
    description: "Fast and reliable cross-chain crypto transfers",
    isComingSoon: false,
    link: "https://layerswap.io/app",
    iconStyling: "p-2",
    icon: "/img/home/layerswap.svg",
  },
  {
    category: "DeFi",
    title: "NooN",
    description: "The intelligent and fair yield-generating stablecoin",
    icon: "/img/home/noon.svg",
    link: "https://app.noon.capital",
    iconStyling: "bg-white",
  },
  {
    category: "Gaming",
    title: "Nova",
    description: "The AI powered Reddit game by Anomaly",
    isComingSoon: false,
    link: "https://www.reddit.com/r/AnomalyGamesInc/",
    icon: "/img/home/nova.jpg",
    iconStyling: "p-1",
  },
  {
    category: "Developers",
    title: "Aethir",
    description: "On-demand GPU computing",
    isComingSoon: false,
    link: "https://aethir.com/",
    icon: "/img/home/aethir.png",
    iconStyling: "bg-white",
  },
  {
    category: "Sophon Essentials",
    title: "Explorer",
    description: "Browse Sophon's transactions, blocks, tokens, and more",
    isComingSoon: false,
    link: "https://explorer.sophon.xyz",
    icon: "/img/home/explorer.svg",
    iconStyling: "bg-white",
  },
  {
    category: "Developers",
    title: "Dev Tooling",
    description: "Discover our rich ecosystem for developers",
    isComingSoon: false,
    link: "https://docs.sophon.xyz/build/partners/overview",
    icon: "/img/home/docs.svg",
  },
  {
    category: "Casino",
    title: "Rivalry",
    description: "The ultimate iGaming platform built by gamers, for gamers",
    isComingSoon: true,
    icon: "/img/home/rivalry.svg",
    iconStyling: "p-1",
  },
  {
    category: "Casino",
    title: "ScorePlay",
    description: "Sports prediction markets enhanced by AI",
    link: "https://www.scoreplay.xyz",
    isComingSoon: true,
    icon: "/img/home/scoreplay.svg",
    iconStyling: "bg-white",
  },
  {
    category: "AI",
    title: "Cod3x",
    description: "Building a 'Giga Swarm' of Social codless Ai Agents",
    link: "https://www.cod3x.org/",
    icon: "/img/home/cod3x.svg",
    isComingSoon: true,
    iconStyling: "bg-white",
  },
  {
    category: "Casino",
    title: "Decentra Degens",
    description: "Online cash poker tournaments",
    link: "https://ddpoker.games/",
    icon: "/img/home/decentradegens.jpg",
    isComingSoon: true,
    iconStyling: "bg-white",
  },
  {
    category: "Gaming",
    title: "Brutal Knights",
    description: "A web3 extraction-roguelike strategy game with a focus on F2P",
    isComingSoon: true,
    icon: "/img/home/brutal.png",
    iconStyling: "bg-white",
  },
  {
    category: "NFT",
    title: "Mintify",
    description:
      "Mintify is the best consumer experience to trade every asset, every network, and every market directly onchain",
    link: "https://mintify.xyz/",
    icon: "/img/home/mintify.svg",
    isComingSoon: true,
    iconStyling: "p-1",
  },
];
